### ISSUE TITLE
bostrom balances

### ISSUE THREAD

**Issue by joeabbey** [ping-pub/explorer#50]
The balances of $BOOT are off by a factor of 1 million:

<img width="600" alt="image" src="https://user-images.githubusercontent.com/759747/147083373-5feb07ec-3864-4f9b-9e92-396cc901eda9.png">

```
 cyber q bank balances bostrom1l2ynn9djxrhwr968cwwhugrjugv482ns5pd804
balances:
- amount: "1000000"
  denom: boot
pagination:
  next_key: null
  total: "0"
```

Let's look at what ping.pub is fetching:

<img width="684" alt="image" src="https://user-images.githubusercontent.com/759747/147084839-d1520e5f-61a5-4a5d-a087-a1c23e374236.png">

```
{"height":"695395","result":[
  {
    "denom": "boot",
    "amount": "1000000"
  }
]}
```

I'm guessing that _every_ other asset tends to provide a `u<asset>` denomination and ping.pub always adjusts by 6 decimals.
